### ISSUE TITLE
Duplicate message in error: in the package.json with the key "packageManager"

### ISSUE THREAD

**Issue by glensc** [pnpm/action-setup#104]
```
Running self-installer...
  Error: No pnpm version is specified.
  Please specify it by one of the following ways:
    - in the GitHub Action config with the key "version"
  Error: Error: No pnpm version is specified.
  Please specify it by one of the following ways:
    - in the GitHub Action config with the key "version"
    - in the package.json with the key "packageManager"
    - in the package.json with the key "packageManager"
      at readTarget (/home/runner/work/_actions/pnpm/action-setup/v2/dist/index.js:1:3939)
      at async runSelfInstaller (/home/runner/work/_actions/pnpm/action-setup/v2/dist/index.js:1:2928)
      at async install (/home/runner/work/_actions/pnpm/action-setup/v2/dist/index.js:1:2239)
      at async main (/home/runner/work/_actions/pnpm/action-setup/v2/dist/index.js:1:445)
```

- https://github.com/glensc/gitlab-webhook-listener-bot/actions/runs/6686055855/job/18165010194?pr=88

**Comment by GaoNeng-wWw** [comment]
```diff
uses: pnpm/action-setup@v2
+  with:
+    version: 8
```
